import type { Metadata } from "next";
import { Encode_Sans } from 'next/font/google'
import '@fortawesome/fontawesome-free/css/all.css'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import Footer from "./_Component/Footer/Footer";
import Navbar from "./_Component/Navbar/Navbar";
import { Toaster } from "@/components/ui/sonner"
import UserSessionProvider from "src/UserSessionProvider";
import CountProvider from "src/CountContext";
const Encode_SansFont = Encode_Sans({
  subsets: ['latin'],
  weight: ['100', '400', '900']
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={Encode_SansFont.className}
      >
        <UserSessionProvider>
          <CountProvider>
            <Navbar />
            <main className="p-5">

              {children}
            </main>
            <Toaster />
            <Footer />

          </CountProvider>
        </UserSessionProvider>
      </body>
    </html>
  );
}
